#include <stdio.h>
main()  
{
//	printf("\n\n\n\t\t\t\t\t\t\t┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\n");
//	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
//	printf("\t\t\t\t\t\t\t┃     ***** 您好,欢迎使用影片信息管理系统! *****     ┃\n");
//	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
//	printf("\t\t\t\t\t\t\t┠────────────────────────────────────────────────────┨\n");
//	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
//	printf("\t\t\t\t\t\t\t┃                ①.录入影片信息                     ┃\n");
//	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
//	printf("\t\t\t\t\t\t\t┃                ②.查找影片信息                     ┃\n");
//	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
//	printf("\t\t\t\t\t\t\t┃                ③.修改影片信息                     ┃\n");
//	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
//	printf("\t\t\t\t\t\t\t┃                ④.删除影片信息                     ┃\n");
//	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
//	printf("\t\t\t\t\t\t\t┃                ⑤.查看影片总数                     ┃\n");
//	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
//	printf("\t\t\t\t\t\t\t┃                ⑥.查看影片信息                     ┃\n");
//	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
//	printf("\t\t\t\t\t\t\t┃                ⑦.影片排序输出                     ┃\n");
//	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
//	printf("\t\t\t\t\t\t\t┃                ⑧.退出系统                         ┃\n"); 
//	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
//	printf("\t\t\t\t\t\t\t┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\n");
//	printf("\n\n\t\t\t\t\t\t\t请在1-7之间进行选择您需要的功能:");
//	
//	printf("\n\n\n\t\t\t\t\t\t\t┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\n");
//	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
//	printf("\t\t\t\t\t\t\t┃               *****    WELCOME    *****            ┃\n");
//	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
//	printf("\t\t\t\t\t\t\t┠────────────────────────────────────────────────────┨\n");
//	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
//	printf("\t\t\t\t\t\t\t┃                 ①. 注册新用户                     ┃\n");
//	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
//	printf("\t\t\t\t\t\t\t┃                 ②. 登陆账户                       ┃\n");
//	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
//	printf("\t\t\t\t\t\t\t┃                 ③. 退出                           ┃\n");
//	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
//	printf("\t\t\t\t\t\t\t┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\n");
//	printf("\n\n\t\t\t\t\t\t\t请在1-3之间进行选择您需要的功能:");

	printf("\n\n\n\t\t\t\t\t\t\t┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\n");
	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
	printf("\t\t\t\t\t\t\t┃                *****查找影片途径****               ┃\n");
	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
	printf("\t\t\t\t\t\t\t┠────────────────────────────────────────────────────┨\n");
	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
	printf("\t\t\t\t\t\t\t┃           请输入下列方式前的序号进行选择           ┃\n");
	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
	printf("\t\t\t\t\t\t\t┃                   1.影片编号                       ┃\n");
	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
	printf("\t\t\t\t\t\t\t┃                   2.影片名称                       ┃\n");
	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
	printf("\t\t\t\t\t\t\t┃                   3.影片主演                       ┃\n");
	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
	printf("\t\t\t\t\t\t\t┃                   4.影片导演                       ┃\n");
	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
	printf("\t\t\t\t\t\t\t┃                   5.影片地区                       ┃\n");
	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
	printf("\t\t\t\t\t\t\t┃                   6.上映时间                       ┃\n");
	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
	printf("\t\t\t\t\t\t\t┃                   7.影片类型                       ┃\n");
	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
	printf("\t\t\t\t\t\t\t┃                   8.影片规格                       ┃\n");
	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
	printf("\t\t\t\t\t\t\t┃                   9.影片评分                       ┃\n");
	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
	printf("\t\t\t\t\t\t\t┃                   0.退出查询                       ┃\n");
	printf("\t\t\t\t\t\t\t┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\n");
	
	printf("\n\n\n\t\t\t\t\t\t\t┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\n");
	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");	
	printf("\t\t\t\t\t\t\t┃                 *****影片排序输出*****             ┃\n");
	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
	printf("\t\t\t\t\t\t\t┠────────────────────────────────────────────────────┨\n");
	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
	printf("\t\t\t\t\t\t\t┃            请输入下列方式前的序号进行选择          ┃\n");
	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
	printf("\t\t\t\t\t\t\t┃                   1.影片编号升序                   ┃\n");
	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
	printf("\t\t\t\t\t\t\t┃                   2.影片编号降序                   ┃\n");
	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
	printf("\t\t\t\t\t\t\t┃                   3.影片名称升序                   ┃\n");
	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
	printf("\t\t\t\t\t\t\t┃                   4.影片名称降序                   ┃\n");
	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
	printf("\t\t\t\t\t\t\t┃                   5.上映时间升序                   ┃\n");
	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
	printf("\t\t\t\t\t\t\t┃                   6.上映时间降序                   ┃\n");
	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
	printf("\t\t\t\t\t\t\t┃                   7.影片评分升序                   ┃\n");
	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
	printf("\t\t\t\t\t\t\t┃                   8.影片评分降序                   ┃\n"); 
	printf("\t\t\t\t\t\t\t┃                                                    ┃\n");
	printf("\t\t\t\t\t\t\t┃                   0.退出查看排序                   ┃\n");
	printf("\t\t\t\t\t\t\t┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\n");
	
} 
